/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package knodb;
import io.grpc.Server;
import io.grpc.ServerBuilder;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException
	{
        Server server = ServerBuilder.forPort(9090)
            .addService(new KnodbOpsServiceImpl())
            .build();

        server.start();
        System.out.println("Server started, listening on " + server.getPort());

        server.awaitTermination();
    }
}
